In [3]:
# Importing the necessary libraries

import torch
import numpy as np

## Tensor Basics

In [4]:
# Creating a matrix
M = torch.tensor([[4,5],
                  [5,2]]) # Matrix and Tensor have to CAPS (industry standard)

In [5]:
# Retrieving elements of a tensor
M[0][0]

tensor(4)

In [6]:
# Creating a tensor(3D)
t = torch.tensor([[[4,5,6],
                   [4,2,4],
                   [4,6,2]],
                  [[3,4,2],
                   [3,2,6],
                   [4,6,2]]])

# Checking the shape of the tensor
t.shape

torch.Size([2, 3, 3])

In [7]:
# Creating a random tensor
random = torch.rand(size=(8,5))
random

tensor([[0.7276, 0.9480, 0.1489, 0.3300, 0.7247],
        [0.9770, 0.2317, 0.5237, 0.1692, 0.1943],
        [0.3223, 0.0650, 0.0435, 0.4795, 0.9878],
        [0.8613, 0.4788, 0.4576, 0.3006, 0.3119],
        [0.5572, 0.4512, 0.5237, 0.9250, 0.5204],
        [0.5231, 0.9591, 0.2275, 0.2804, 0.6944],
        [0.1566, 0.0940, 0.6242, 0.9918, 0.8617],
        [0.3299, 0.0664, 0.3814, 0.8496, 0.5294]])

In [8]:
# Creating a tensor of zeroes
z = torch.zeros(size = (2,4))
z

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [9]:
# Creating a tensor of ones
o = torch.ones(size = (4,4))
o

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [10]:
# A range of numbers with steps
num_list = torch.arange(start=25, end=50, step = 3)
num_list

tensor([25, 28, 31, 34, 37, 40, 43, 46, 49])

In [11]:
# Like functions of pytorch
num_zeros = torch.zeros_like(input = num_list)
num_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
# Verifying the shapes of 'like'
num_zeros.shape == num_list.shape

True

In [13]:
# Checking different dtypes
a = torch.rand(size = (3,3))
print(a)
print(a.dtype)

print()

b = torch.rand(size = (3,3), dtype = torch.float16)
print(b)
print(b.dtype)

tensor([[0.7530, 0.4017, 0.6917],
        [0.1271, 0.2720, 0.9327],
        [0.6947, 0.5528, 0.0167]])
torch.float32

tensor([[0.6934, 0.3862, 0.7056],
        [0.5581, 0.1196, 0.3716],
        [0.4521, 0.9478, 0.4106]], dtype=torch.float16)
torch.float16


In [14]:
# Checking the resulting dtype
c = a * b
print(c.dtype) # chooses the dtype which is larger

torch.float32


In [15]:
# Verifying the resulting dtype
c = c.type(torch.float16)
print(c.dtype)

d = c * b
print(d.dtype)

torch.float16
torch.float16


## Tensor Operations

In [16]:
# Basic operations
x = torch.tensor([[1,2,3],
                  [4,5,6]])

print(x)

print()
print("Addition")
print(x + 10)

print()
print("Subtraction")
print(x - 10)

print()
print("Scalar Multiplication")
print(x * 10)

print()
print("Division")
print(x / 10)

tensor([[1, 2, 3],
        [4, 5, 6]])

Addition
tensor([[11, 12, 13],
        [14, 15, 16]])

Subtraction
tensor([[-9, -8, -7],
        [-6, -5, -4]])

Scalar Multiplication
tensor([[10, 20, 30],
        [40, 50, 60]])

Division
tensor([[0.1000, 0.2000, 0.3000],
        [0.4000, 0.5000, 0.6000]])


In [17]:
# Other available functions for basic operations
print(x.add(10))

print()

print(torch.add(x,10))

tensor([[11, 12, 13],
        [14, 15, 16]])

tensor([[11, 12, 13],
        [14, 15, 16]])


In [18]:
# Matrix multiplication (dot product)
a = torch.tensor([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

c = a.matmul(a)
print(c)

tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])


In [19]:
# Operator for matrix multiplication
print(a @ a)

print()

# Other function for matrix multiplication
print(torch.mm(a,a))

tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])


In [20]:
# Bigger tensor with time taken
%time
a = torch.rand(size=(20,25))
b = torch.rand(size=(25,30))
c = a.matmul(b)

print(c.shape)

CPU times: user 2 μs, sys: 0 ns, total: 2 μs
Wall time: 5.48 μs
torch.Size([20, 30])


In [21]:
# Matrix Transpose
a = torch.rand(size=(3,2))
print(a)

print()

print("Matrix Transposed")
print(a.T)

print()

b = torch.matmul(a, a.T)
print(b)

tensor([[0.7164, 0.4760],
        [0.3728, 0.0461],
        [0.0887, 0.1733]])

Matrix Transposed
tensor([[0.7164, 0.3728, 0.0887],
        [0.4760, 0.0461, 0.1733]])

tensor([[0.7397, 0.2890, 0.1460],
        [0.2890, 0.1411, 0.0410],
        [0.1460, 0.0410, 0.0379]])


## Tensor Aggregation

In [22]:
# Random tensor
x = torch.randint(high = 100, size=(3,4))
x = x.type(torch.float32)
x

tensor([[78., 73., 56., 65.],
        [15., 47., 57., 55.],
        [ 7., 63., 88., 85.]])

In [23]:
# Min
print(torch.min(x))
print(x.min())
print()

# Max
print(x.max())
print()

# Mean
print(x.mean())

# Sum
print(x.sum())

tensor(7.)
tensor(7.)

tensor(88.)

tensor(57.4167)
tensor(689.)


In [24]:
# Positinal Min, Max (Arg Min, Max)
print("Position of min:")
print(x.argmin())
print()

print("Postion of max:")
print(x.argmax())

Position of min:
tensor(8)

Postion of max:
tensor(10)


## Dimensional Manipulation

In [25]:
# Creating a random tensor
x = torch.randint(high = 100, size = (4,4))
print(x)

tensor([[ 8, 25, 63, 64],
        [64, 63, 84, 27],
        [13, 46, 40, 11],
        [42,  0, 92, 28]])


### Reshaping

The function `torch.reshape()` will assist in reshaping the input tensor.

The shape has to be compatible. <br>
ie, the number of elements has to be the same for desired shape and the input shape.

In [26]:
# Demonstrating reshape
a = torch.reshape(x, shape = (8,2))
print(a)

print()

b = torch.reshape(x, shape = (2,2,4))
print(b)

tensor([[ 8, 25],
        [63, 64],
        [64, 63],
        [84, 27],
        [13, 46],
        [40, 11],
        [42,  0],
        [92, 28]])

tensor([[[ 8, 25, 63, 64],
         [64, 63, 84, 27]],

        [[13, 46, 40, 11],
         [42,  0, 92, 28]]])


### View

The function `<Tensor>.view()` will alter the view of the tensor to a different shape while sharing the same memory of the object (There is no copy created, just a different view).

ie,
`a = x.view(size)` <br>
Altering the values of `a` will also alter the original tensor `x` and vice versa.

In [27]:
# Demonstrating <Tensor>.view()
a = x.view(size = (8,2))
print(a)
print()

# Altering 'a'
a += 100
print(a)
print()

# Tracking changes in 'x'
print(x)

tensor([[ 8, 25],
        [63, 64],
        [64, 63],
        [84, 27],
        [13, 46],
        [40, 11],
        [42,  0],
        [92, 28]])

tensor([[108, 125],
        [163, 164],
        [164, 163],
        [184, 127],
        [113, 146],
        [140, 111],
        [142, 100],
        [192, 128]])

tensor([[108, 125, 163, 164],
        [164, 163, 184, 127],
        [113, 146, 140, 111],
        [142, 100, 192, 128]])


### Stacking

To stack different tensors. The stacking of tensors happens in a new dimension. 

Look at `torch.cat` for concatenation of tensors.

In [28]:
print(x)
print(x.shape)
print()

a = torch.stack([x,x], dim = 0)
print(a)
print(a.shape) # 2, 4, 4
print()

b = torch.stack([x,x], dim = 1)
print(b)
print(b.shape) # 4, 2, 4
print()

c = torch.stack([x,x], dim = 2)
print(c)
print(c.shape) # 4, 4, 2

tensor([[108, 125, 163, 164],
        [164, 163, 184, 127],
        [113, 146, 140, 111],
        [142, 100, 192, 128]])
torch.Size([4, 4])

tensor([[[108, 125, 163, 164],
         [164, 163, 184, 127],
         [113, 146, 140, 111],
         [142, 100, 192, 128]],

        [[108, 125, 163, 164],
         [164, 163, 184, 127],
         [113, 146, 140, 111],
         [142, 100, 192, 128]]])
torch.Size([2, 4, 4])

tensor([[[108, 125, 163, 164],
         [108, 125, 163, 164]],

        [[164, 163, 184, 127],
         [164, 163, 184, 127]],

        [[113, 146, 140, 111],
         [113, 146, 140, 111]],

        [[142, 100, 192, 128],
         [142, 100, 192, 128]]])
torch.Size([4, 2, 4])

tensor([[[108, 108],
         [125, 125],
         [163, 163],
         [164, 164]],

        [[164, 164],
         [163, 163],
         [184, 184],
         [127, 127]],

        [[113, 113],
         [146, 146],
         [140, 140],
         [111, 111]],

        [[142, 142],
         [100, 100],
     

### Squeeze and Unsqueeze

The `Tensor.squeeze()` function removes all the single dimensions in a tensor. The `Tensor.unsqueeze()` function add a single dimension at the given position.

In [29]:
# Create a random array
x = torch.rand(size=(4,3,1,2,1))
print(x.shape)

torch.Size([4, 3, 1, 2, 1])


In [30]:
# Demonstrating squeeze function
y = x.squeeze()
print(y.shape)

torch.Size([4, 3, 2])


In [31]:
# Demonstrating unsqueeze function
z = y.unsqueeze(dim=1)
print(z.shape)

torch.Size([4, 1, 3, 2])


### Permute

The `Tensor.permute()` function will rearrange the dimensions of a tensor to a specific given order. 

This function returns a `view`. ie, the changes occured in one will show in the other.

In [32]:
# Shape of a tensor
x.shape

torch.Size([4, 3, 1, 2, 1])

In [33]:
# Demonstrating permute()
y = x.permute(4, 2, 1, 0, 3)
y.shape

torch.Size([1, 1, 3, 4, 2])

In [34]:
# Verifying the 'view' aspect by using 'sum()'
print(x.sum())
print()

y += 1
print(x.sum()) # Each element raised by 1 (24 elements)

tensor(12.7454)

tensor(36.7454)


## Indexing

In [35]:
# Create a random tensor
x = torch.rand(size=(3, 2))
print(x)

tensor([[0.4089, 0.5780],
        [0.2765, 0.9687],
        [0.3533, 0.3963]])


In [36]:
# Demonstrating specific indicies
print(x[0])

print()

print(x[0][1])

print()

print(x[0, 1])

tensor([0.4089, 0.5780])

tensor(0.5780)

tensor(0.5780)


In [37]:
# Demonstrating specific range
print(x)

print()

print(x[:, 0]) # First column

print()

print(x[:2, 0]) # First two elements of first column

print()

print(x[1, :]) # Second row

tensor([[0.4089, 0.5780],
        [0.2765, 0.9687],
        [0.3533, 0.3963]])

tensor([0.4089, 0.2765, 0.3533])

tensor([0.4089, 0.2765])

tensor([0.2765, 0.9687])


## PyTorch and NumPy

Converting from NumPy to PyTorch or vice versa. NumPy is popular while handling and manipulating data, PyTorch is popular for deep learning.

- To convert NumPy `ndarray` to PyTorch `tensor` - `torch.from_numpy()` <br>
- To convert PyTorch `tensor` to NumPy `ndarray` - `Tensor.numpy()` <br>

**Warning**:
- For the above mentioned functions, any changes to one object will reflect in the other. They share the same memory. **use `torch.tensor` to create a copy.**
- The default `dtype` of NumPy is `float64` whereas PyTorch uses `float32`.

In [38]:
# A range of numbers
a = np.arange(1.0, 10.0)
a

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [39]:
# Convering it to tensor
b = torch.from_numpy(a)
b

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64)

In [40]:
# Changing the ndarray object which reflects in tensor
a += 1

print(a)
print()
print(b)

[ 2.  3.  4.  5.  6.  7.  8.  9. 10.]

tensor([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=torch.float64)


In [41]:
# Generating random numbers using NumPy [0,1)
def_rng = np.random.default_rng()
x = def_rng.random(size = (3,4))
print(x)
print()

# Convert to tensor without sharing memory
y = torch.tensor(x)
print(y)
print(type(y))
print()

x += 1
print(y)

[[0.55149378 0.24005318 0.53260238 0.54580144]
 [0.43573935 0.71033031 0.22043531 0.20448691]
 [0.91806012 0.28191468 0.93662012 0.05311328]]

tensor([[0.5515, 0.2401, 0.5326, 0.5458],
        [0.4357, 0.7103, 0.2204, 0.2045],
        [0.9181, 0.2819, 0.9366, 0.0531]], dtype=torch.float64)
<class 'torch.Tensor'>

tensor([[0.5515, 0.2401, 0.5326, 0.5458],
        [0.4357, 0.7103, 0.2204, 0.2045],
        [0.9181, 0.2819, 0.9366, 0.0531]], dtype=torch.float64)


## Loading tensors on the GPU

In [42]:
# Check available GPUs
!nvidia-smi

Mon Oct 28 12:00:56 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.35.03              Driver Version: 560.81         CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3060 ...    On  |   00000000:01:00.0  On |                  N/A |
| N/A   49C    P8             14W /   77W |     493MiB /   6144MiB |      4%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [43]:
# Device agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


In [44]:
# Creating a tensor on GPU
x = torch.rand(size = (3,4), device = device)
print(x)

tensor([[0.3984, 0.5701, 0.9526, 0.3052],
        [0.4218, 0.3641, 0.8012, 0.1967],
        [0.8016, 0.9577, 0.0884, 0.5211]], device='cuda:0')


In [45]:
# Moving a tensor from CPU to GPU
x = torch.rand(size=(3,4))
print(x.device)
print()

x_gpu = x.to(device)
print(x_gpu.device)

cpu

cuda:0


In [46]:
# Moving a tensor from GPU to CPU
    # Note: NumPy doesn't work on GPU, need to move before using numpy features
x_cpu = x_gpu.cpu()
print(x_cpu.device)

cpu
