In [1]:
# Importing the necessary libraries

import torch
import numpy as np

## Tensor Basics

In [2]:
# Creating a matrix
M = torch.tensor([[4,5],
                  [5,2]]) # Matrix and Tensor have to CAPS (industry standard)

In [3]:
# Retrieving elements of a tensor
M[0][0]

tensor(4)

In [4]:
# Creating a tensor(3D)
t = torch.tensor([[[4,5,6],
                   [4,2,4],
                   [4,6,2]],
                  [[3,4,2],
                   [3,2,6],
                   [4,6,2]]])

# Checking the shape of the tensor
t.shape

torch.Size([2, 3, 3])

In [5]:
# Creating a random tensor
random = torch.rand(size=(8,5))
random

tensor([[0.0110, 0.8272, 0.8948, 0.7311, 0.1987],
        [0.6448, 0.6365, 0.7268, 0.1646, 0.0253],
        [0.9347, 0.5036, 0.7598, 0.5117, 0.7501],
        [0.4225, 0.2516, 0.7181, 0.3777, 0.8801],
        [0.2208, 0.0334, 0.3422, 0.2826, 0.4822],
        [0.7364, 0.1137, 0.6138, 0.5805, 0.0865],
        [0.9373, 0.5806, 0.2282, 0.4219, 0.6555],
        [0.1835, 0.7646, 0.2714, 0.5790, 0.5810]])

In [6]:
# Creating a tensor of zeroes
z = torch.zeros(size = (2,4))
z

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [7]:
# Creating a tensor of ones
o = torch.ones(size = (4,4))
o

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [8]:
# A range of numbers with steps
num_list = torch.arange(start=25, end=50, step = 3)
num_list

tensor([25, 28, 31, 34, 37, 40, 43, 46, 49])

In [9]:
# Like functions of pytorch
num_zeros = torch.zeros_like(input = num_list)
num_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
# Verifying the shapes of 'like'
num_zeros.shape == num_list.shape

True

In [11]:
# Checking different dtypes
a = torch.rand(size = (3,3))
print(a)
print(a.dtype)

print()

b = torch.rand(size = (3,3), dtype = torch.float16)
print(b)
print(b.dtype)

tensor([[0.4341, 0.6821, 0.7790],
        [0.6710, 0.3034, 0.2136],
        [0.0865, 0.3179, 0.1942]])
torch.float32

tensor([[0.5732, 0.2593, 0.7124],
        [0.2197, 0.2446, 0.2275],
        [0.0669, 0.1426, 0.0977]], dtype=torch.float16)
torch.float16


In [12]:
# Checking the resulting dtype
c = a * b
print(c.dtype) # chooses the dtype which is larger

torch.float32


In [13]:
# Verifying the resulting dtype
c = c.type(torch.float16)
print(c.dtype)

d = c * b
print(d.dtype)

torch.float16
torch.float16


## Tensor Operations

In [14]:
# Basic operations
x = torch.tensor([[1,2,3],
                  [4,5,6]])

print(x)

print()
print("Addition")
print(x + 10)

print()
print("Subtraction")
print(x - 10)

print()
print("Scalar Multiplication")
print(x * 10)

print()
print("Division")
print(x / 10)

tensor([[1, 2, 3],
        [4, 5, 6]])

Addition
tensor([[11, 12, 13],
        [14, 15, 16]])

Subtraction
tensor([[-9, -8, -7],
        [-6, -5, -4]])

Scalar Multiplication
tensor([[10, 20, 30],
        [40, 50, 60]])

Division
tensor([[0.1000, 0.2000, 0.3000],
        [0.4000, 0.5000, 0.6000]])


In [15]:
# Other available functions for basic operations
print(x.add(10))

print()

print(torch.add(x,10))

tensor([[11, 12, 13],
        [14, 15, 16]])

tensor([[11, 12, 13],
        [14, 15, 16]])


In [16]:
# Matrix multiplication (dot product)
a = torch.tensor([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

c = a.matmul(a)
print(c)

tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])


In [17]:
# Operator for matrix multiplication
print(a @ a)

print()

# Other function for matrix multiplication
print(torch.mm(a,a))

tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])


In [18]:
# Bigger tensor with time taken
%time
a = torch.rand(size=(20,25))
b = torch.rand(size=(25,30))
c = a.matmul(b)

print(c.shape)

CPU times: user 2 μs, sys: 0 ns, total: 2 μs
Wall time: 6.2 μs
torch.Size([20, 30])


In [19]:
# Matrix Transpose
a = torch.rand(size=(3,2))
print(a)

print()

print("Matrix Transposed")
print(a.T)

print()

b = torch.matmul(a, a.T)
print(b)

tensor([[0.6424, 0.4477],
        [0.3921, 0.5673],
        [0.4281, 0.7961]])

Matrix Transposed
tensor([[0.6424, 0.3921, 0.4281],
        [0.4477, 0.5673, 0.7961]])

tensor([[0.6131, 0.5058, 0.6314],
        [0.5058, 0.4755, 0.6195],
        [0.6314, 0.6195, 0.8171]])


## Tensor Aggregation

In [20]:
# Random tensor
x = torch.randint(high = 100, size=(3,4))
x = x.type(torch.float32)
x

tensor([[39., 58., 93., 64.],
        [66., 91., 50., 80.],
        [61., 18.,  7., 61.]])

In [21]:
# Min
print(torch.min(x))
print(x.min())
print()

# Max
print(x.max())
print()

# Mean
print(x.mean())

# Sum
print(x.sum())

tensor(7.)
tensor(7.)

tensor(93.)

tensor(57.3333)
tensor(688.)


In [22]:
# Positinal Min, Max (Arg Min, Max)
print("Position of min:")
print(x.argmin())
print()

print("Postion of max:")
print(x.argmax())

Position of min:
tensor(10)

Postion of max:
tensor(2)


## Dimensional Manipulation

In [23]:
# Creating a random tensor
x = torch.randint(high = 100, size = (4,4))
print(x)

tensor([[11, 98, 10, 19],
        [69, 39, 19,  6],
        [64, 93, 11, 15],
        [16, 95, 98, 25]])


### Reshaping

The function `torch.reshape()` will assist in reshaping the input tensor.

The shape has to be compatible. <br>
ie, the number of elements has to be the same for desired shape and the input shape.

In [24]:
# Demonstrating reshape
a = torch.reshape(x, shape = (8,2))
print(a)

print()

b = torch.reshape(x, shape = (2,2,4))
print(b)

tensor([[11, 98],
        [10, 19],
        [69, 39],
        [19,  6],
        [64, 93],
        [11, 15],
        [16, 95],
        [98, 25]])

tensor([[[11, 98, 10, 19],
         [69, 39, 19,  6]],

        [[64, 93, 11, 15],
         [16, 95, 98, 25]]])


### View

The function `<Tensor>.view()` will alter the view of the tensor to a different shape while sharing the same memory of the object (There is no copy created, just a different view).

ie,
`a = x.view(size)` <br>
Altering the values of `a` will also alter the original tensor `x` and vice versa.

In [25]:
# Demonstrating <Tensor>.view()
a = x.view(size = (8,2))
print(a)
print()

# Altering 'a'
a += 100
print(a)
print()

# Tracking changes in 'x'
print(x)

tensor([[11, 98],
        [10, 19],
        [69, 39],
        [19,  6],
        [64, 93],
        [11, 15],
        [16, 95],
        [98, 25]])

tensor([[111, 198],
        [110, 119],
        [169, 139],
        [119, 106],
        [164, 193],
        [111, 115],
        [116, 195],
        [198, 125]])

tensor([[111, 198, 110, 119],
        [169, 139, 119, 106],
        [164, 193, 111, 115],
        [116, 195, 198, 125]])


### Stacking

To stack different tensors. You can choose to do it horizontally or vertically using `dim` argument. You could also stack in different dimensions for higher dimensional tensors.

In [33]:
print(x)
print(x.shape)
print()

a = torch.stack([x,x], dim = 0)
print(a)
print(a.shape) # 2, 4, 4
print()

b = torch.stack([x,x], dim = 1)
print(b)
print(b.shape) # 4, 2, 4
print()

c = torch.stack([x,x], dim = 2)
print(c)
print(c.shape) # 4, 4, 2

tensor([[111, 198, 110, 119],
        [169, 139, 119, 106],
        [164, 193, 111, 115],
        [116, 195, 198, 125]])
torch.Size([4, 4])

tensor([[[111, 198, 110, 119],
         [169, 139, 119, 106],
         [164, 193, 111, 115],
         [116, 195, 198, 125]],

        [[111, 198, 110, 119],
         [169, 139, 119, 106],
         [164, 193, 111, 115],
         [116, 195, 198, 125]]])
torch.Size([2, 4, 4])

tensor([[[111, 198, 110, 119],
         [111, 198, 110, 119]],

        [[169, 139, 119, 106],
         [169, 139, 119, 106]],

        [[164, 193, 111, 115],
         [164, 193, 111, 115]],

        [[116, 195, 198, 125],
         [116, 195, 198, 125]]])
torch.Size([4, 2, 4])

tensor([[[111, 111],
         [198, 198],
         [110, 110],
         [119, 119]],

        [[169, 169],
         [139, 139],
         [119, 119],
         [106, 106]],

        [[164, 164],
         [193, 193],
         [111, 111],
         [115, 115]],

        [[116, 116],
         [195, 195],
     

### Squeeze and Unsqueeze

The `Tensor.squeeze()` function removes all the single dimensions in a tensor. The `Tensor.unsqueeze()` function add a single dimension at the given position.

In [35]:
# Create a random array
x = torch.rand(size=(4,3,1,2,1))
print(x.shape)

torch.Size([4, 3, 1, 2, 1])


In [37]:
# Demonstrating squeeze function
y = x.squeeze()
print(y.shape)

torch.Size([4, 3, 2])


In [39]:
# Demonstrating unsqueeze function
z = y.unsqueeze(dim=1)
print(z.shape)

torch.Size([4, 1, 3, 2])


### Permute

The `Tensor.permute()` function will rearrange the dimensions of a tensor to a specific given order. <br>
This function returns a `view`. ie, the changes occured in one will show in the other.

In [40]:
# Shape of a tensor
x.shape

torch.Size([4, 3, 1, 2, 1])

In [44]:
# Demonstrating permute()
y = x.permute(4, 2, 1, 0, 3)
y.shape

torch.Size([1, 1, 3, 4, 2])

In [46]:
# Verifying the 'view' aspect by using 'sum()'
print(x.sum())
print()

y += 1
print(x.sum()) # Each element raised by 1 (24 elements)

tensor(14.4183)

tensor(38.4183)
